print -P "%F{$ZSH_PROMPT_COLOR_PWD}%~%f"| read PS1
PS1+=`print -P $'\n'%F{$ZSH_PROMPT_SYMBOL_COLOR}$ZSH_PROMPT_SYMBOL%f %F{green}command%f arg1 arg2 ... argn`

git rev-parse --short HEAD 2> /dev/null | read
RPS1="%F{$ZSH_PROMPT_COLOR_REVISION}$ZSH_PROMPT_SYMBOL_REVISION%f${REPLY:-ae67f4e} "
git remote 2> /dev/null | read
RPS1+="%F{$ZSH_PROMPT_COLOR_BRANCH}${ZSH_PROMPT_SYMBOL_BRANCH}%f${REPLY:-origin}/master"
RPS1+="%F{$ZSH_PROMPT_COLOR_UNTRACKED}${ZSH_PROMPT_SYMBOL_UNTRACKED}%f"
RPS1+="%F{$ZSH_PROMPT_COLOR_MODIFIED}$ZSH_PROMPT_SYMBOL_MODIFIED%f$ZWJ"
RPS1+="%F{$ZSH_PROMPT_COLOR_DELETED}$ZSH_PROMPT_SYMBOL_DELETED%f$ZWJ"
RPS1+="%U%F{$ZSH_PROMPT_COLOR_RENAMED}$ZSH_PROMPT_SYMBOL_RENAMED%f%u$ZWJ"
RPS1+="%U%F{$ZSH_PROMPT_COLOR_ADDED}$ZSH_PROMPT_SYMBOL_ADDED%f%u$ZWJ"
RPS1+="%U%F{$ZSH_PROMPT_COLOR_MODIFIED}$ZSH_PROMPT_SYMBOL_MODIFIED%f%u$ZWJ"
RPS1+="%F{$ZSH_PROMPT_COLOR_STASHED}$ZSH_PROMPT_SYMBOL_STASHED%f"
RPS1+="7${ZSH_PROMPT_SYMBOL_BEHIND}2$ZSH_PROMPT_SYMBOL_AHEAD"

print -P $RPS1 | read RPS1
printf 'mnml theme:\n%s%*s%s\n' $PS1 $(($COLUMNS * 2 + 36)) $RPS1
